
// Generated by tools/generate_license_notice.py. Do not modify.

#ifndef PACKAGER_TOOLS_LICENSE_NOTICE_H_
#define PACKAGER_TOOLS_LICENSE_NOTICE_H_

namespace shaka {
extern const char* kLicenseNotice[1186];
}  // namespace shaka

#endif  // PACKAGER_TOOLS_LICENSE_NOTICE_H_